In [1]:
import numpy as np 

In [5]:
ls = [[1,2,3,4]]
arr = np.array(ls)
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr.shape

(1, 4)

In [7]:
l = [[1,2,3],[4,5,6]]
arr = np.array(l)
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
arr.dtype

dtype('int64')

In [17]:
np.array([12, 43, 23, 5.7, 4+89j], dtype='complex')

array([12.  +0.j, 43.  +0.j, 23.  +0.j,  5.7 +0.j,  4. +89.j])

In [21]:
arr1 = np.array([[12,34,54],[23, 65, None],[76+89j, 89.7,98]])

In [23]:
np.arange(1.4,7.8)

array([1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4])

In [26]:
np.arange(1.8,40, 5.5)

array([ 1.8,  7.3, 12.8, 18.3, 23.8, 29.3, 34.8])

In [27]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
# you cannot do arr.reshape(3,1) or (1, 2) ...etc 
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
print(arr.reshape(6))
arr.reshape(6,1)

[1 2 3 4 5 6]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
np.ones(6)

numpy.ndarray

In [43]:
np.full(10,7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [44]:
np.full([2,3],5)

array([[5, 5, 5],
       [5, 5, 5]])

In [46]:
np.full([2,3],[1,3,5])

array([[1, 3, 5],
       [1, 3, 5]])

In [54]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
np.random.randint(1,10,5)

array([1, 9, 6, 6, 1])

In [62]:
np.random.randint(1,10)

6

In [63]:
np.random.rand(6)

array([0.95012825, 0.67490105, 0.97775116, 0.51227561, 0.19003373,
       0.21201597])

In [67]:
np.random.rand(1, 10, 3)

array([[[0.55924204, 0.2258984 , 0.78603396],
        [0.5800394 , 0.99989538, 0.40263727],
        [0.28357394, 0.88754708, 0.88669862],
        [0.31339834, 0.42607122, 0.91604935],
        [0.40858568, 0.52015448, 0.76399143],
        [0.20427492, 0.83938724, 0.1708563 ],
        [0.94817513, 0.48305045, 0.15022353],
        [0.39719589, 0.04476779, 0.71439675],
        [0.26079349, 0.26670614, 0.25688163],
        [0.23612256, 0.9840847 , 0.51845353]]])

In [77]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.linspace(2,10, retstep=True)

(array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
         2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
         3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
         4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
         5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
         6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
         6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
         7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
         8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
         9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ]),
 np.float64(0.16326530612244897))

In [79]:
np.arange(2, 11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr = np.arange(2, 11).reshape([3,3])
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

#### **copy and view**

In [87]:
new_arr = arr.view()
new_arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [88]:
arr[0][0] = 100;
arr

array([[100,   3,   4],
       [  5,   6,   7],
       [  8,   9,  10]])

In [89]:
new_arr_copy = arr.copy()
new_arr_copy

array([[100,   3,   4],
       [  5,   6,   7],
       [  8,   9,  10]])